### ISSUE TITLE
Core.Async Todo blog post no longer working

### ISSUE THREAD

**Issue by jimmyhmiller** [bhauman/bhauman.github.com#5]
When I visit this post in both Firefox and Chrome none of the examples work and I get the following in my console.
```
uncaught exception: Invalid match arg: /\./
```
I know this blog post is from years ago at this point. But it does such an amazing job showing a practical example of core.async I'd love to be able to point people to it.

http://rigsomelight.com/2013/07/18/clojurescript-core-async-todos.html

Thanks for the great post. Let me know if I can help in anyway.

**Comment by bhauman** [comment]
Thanks for pointing this out!  I'm going to need to recompile it.
